version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: meneame_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  php:
    build: ./docker
    container_name: meneame_php
    restart: always
    ports:
      - "9003:9003" 
    volumes:
      - ./www:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 start_with_request=yes"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: meneame_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meneame
      MYSQL_USER: meneame_user
      MYSQL_PASSWORD: meneame_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/meneame.sql:/docker-entrypoint-initdb.d/meneame.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meneame_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
